services:
  # Markr Application
  app:
    build: . # Building from current dir
    container_name: markr_app
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app # Mount current dir to /usr/src/app
      - /usr/src/app/node_modules # Prevent overriding node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - markr_network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: markr_postgres_db
    restart: unless-stopped
    environment:
      # These are needed for pg_isready and for initializing the database
      # They can also be in the .env file for other services to use
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: # You can still load other shared variables if needed
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - markr_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Test Runner
  test:
    build: .
    container_name: markr_test
    command: ["sh", "-c", "./scripts/wait-for-postgres.sh"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles: ["test"]
    volumes:
      - .:/usr/src/app
    networks:
      - markr_network

volumes:
  postgres_data:

networks:
  markr_network:
    driver: bridge
